/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario Garcia
 */
public class BuscarClientes extends javax.swing.JFrame {

    /**
     * Creates new form BuscarClientes
     */
    
    MySqlConn objConn=new MySqlConn();
    
    public BuscarClientes(MySqlConn conn){
        this.objConn=objConn;
        initComponents(); 
    }
    public BuscarClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextFieldhabitacion.setBorder(null);
        jTextFieldhabitacion.setOpaque(false);
        jTextFieldhabitacion.setBackground(new Color(0,0,0,48));
        jTextFieldnombre.setBorder(null);
        jTextFieldnombre.setOpaque(false);
        jTextFieldnombre.setBackground(new Color(0,0,0,48));
        jButtonRegresar.setOpaque(false);
        jButtonRegresar.setBackground(new Color(0,0,0,32));
        jButtonBuscarNombre.setOpaque(false);
        jButtonBuscarNombre.setBackground(new Color(0,0,0,32));
        jButtonBuscarHabitacion.setOpaque(false);
        jButtonBuscarHabitacion.setBackground(new Color(0,0,0,32));
        jTextFieldBuscarNombre.setBorder(null);
        jTextFieldBuscarNombre.setOpaque(false);
        jTextFieldBuscarNombre.setBackground(new Color(0,0,0,48));
        jTextFieldBuscarHabitacion.setBorder(null);
        jTextFieldBuscarHabitacion.setOpaque(false);
        jTextFieldBuscarHabitacion.setBackground(new Color(0,0,0,48));
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBuscarNombre = new javax.swing.JTextField();
        jTextFieldBuscarHabitacion = new javax.swing.JTextField();
        jButtonBuscarNombre = new javax.swing.JButton();
        jButtonBuscarHabitacion = new javax.swing.JButton();
        jTextFieldhabitacion = new javax.swing.JTextField();
        jTextFieldnombre = new javax.swing.JTextField();
        jButtonRegresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setText("Buscar por Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setText("Buscar por Habitacion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jTextFieldBuscarNombre.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldBuscarNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 230, 50));

        jTextFieldBuscarHabitacion.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldBuscarHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldBuscarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 120, 50));

        jButtonBuscarNombre.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jButtonBuscarNombre.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarNombre.setText("Buscar");
        jButtonBuscarNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 160, 50));

        jButtonBuscarHabitacion.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jButtonBuscarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarHabitacion.setText("Buscar");
        jButtonBuscarHabitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 160, 50));

        jTextFieldhabitacion.setEditable(false);
        jTextFieldhabitacion.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldhabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 380, 60));

        jTextFieldnombre.setEditable(false);
        jTextFieldnombre.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 380, 60));

        jButtonRegresar.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("<- Regresar");
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 403, 120, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>                        

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        Consulta cons = new Consulta();
        cons.setVisible(true);
        dispose();
    }                                               

    private void jButtonBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        String h = this.jTextFieldBuscarNombre.getText().trim();
        
        List<Clientes> lista = new ArrayList<Clientes>();
        
        if(h.isEmpty()){
            JOptionPane.showMessageDialog(this, "Huesped no registrado");
            
        }else{

        try{
            Statement st = objConn.conn.createStatement();
            String query1 = "select * from clientes";
            ResultSet rs = st.executeQuery(query1);
            String nombre1, ciudad1, tipo1, fechasalida1, fechaentrada1;
            int total1, habitacion1;
            lista.removeAll(lista);
            while(rs.next()){
                nombre1 = rs.getString("nombre");
                ciudad1 = rs.getString("ciudad");
                tipo1 = rs.getString("tipo");
                fechasalida1 = rs.getString("fechasalida");
                fechaentrada1 = rs.getString("fechaentrada");
                total1 = rs.getInt("total");
                habitacion1 = rs.getInt("habitacion");
                Clientes c;
                c = new Clientes(nombre1, ciudad1, tipo1,total1,fechasalida1, fechaentrada1, habitacion1);
                
                if(h.equals(nombre1)){
                    jTextFieldnombre.setText( " "+nombre1+" esta en la habitacion: "+habitacion1 );
                }
                
                
                lista.add(c);
            }
            
        }catch(SQLException sqle){
            System.out.println("Error SQL....." + sqle);
        }
    }
        
        
        
    }                                                   

    private void jButtonBuscarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
        int h1;
        String h = this.jTextFieldBuscarHabitacion.getText().trim();
        h1 = Integer.parseInt(h);
        List<Clientes> lista = new ArrayList<Clientes>();
        
        if(h.isEmpty()){
            JOptionPane.showMessageDialog(this, "Numero de habitacion vacio");
            
        }else{

        try{
            Statement st = objConn.conn.createStatement();
            String query1 = "select * from clientes";
            ResultSet rs = st.executeQuery(query1);
            String nombre1, ciudad1, tipo1, fechasalida1, fechaentrada1;
            int total1, habitacion1;
            lista.removeAll(lista);
            while(rs.next()){
                nombre1 = rs.getString("nombre");
                ciudad1 = rs.getString("ciudad");
                tipo1 = rs.getString("tipo");
                fechasalida1 = rs.getString("fechasalida");
                fechaentrada1 = rs.getString("fechaentrada");
                total1 = rs.getInt("total");
                habitacion1 = rs.getInt("habitacion");
                Clientes c;
                c = new Clientes(nombre1, ciudad1, tipo1,total1,fechasalida1, fechaentrada1, habitacion1);
                
                if(h1 == habitacion1){
                    jTextFieldhabitacion.setText("Habitacion ocupada por : " + nombre1 );
                }
                
                
                lista.add(c);
            }
            
        }catch(SQLException sqle){
            System.out.println("Error SQL....." + sqle);
        }
    }
        
    }                                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonBuscarHabitacion;
    private javax.swing.JButton jButtonBuscarNombre;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldBuscarHabitacion;
    private javax.swing.JTextField jTextFieldBuscarNombre;
    private javax.swing.JTextField jTextFieldhabitacion;
    private javax.swing.JTextField jTextFieldnombre;
    // End of variables declaration                   
}
