/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

/**
 *
 * @author Noé
 */
public class Recibo extends javax.swing.JFrame {

    /**
     * Creates new form Recibo
     */
    public Recibo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelLema = new javax.swing.JLabel();
        jLabelRecibo = new javax.swing.JLabel();
        jLabelUbicacion = new javax.swing.JLabel();
        jLabelNombreHotel = new javax.swing.JLabel();
        jScrollPanelEscritura = new javax.swing.JScrollPane();
        jTextAreaRECIBO = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFondo = new javax.swing.JTextArea();
        jButtonMenu = new javax.swing.JButton();
        Fondo2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoh1.png"))); // NOI18N
        jLabelLogo.setText("jLabel2");
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 140, 140));

        jLabelLema.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabelLema.setText("\"Trabajamos para su comodidad\"");
        getContentPane().add(jLabelLema, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 250, 60));

        jLabelRecibo.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabelRecibo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRecibo.setText("*************************************************");
        getContentPane().add(jLabelRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 350, 20));

        jLabelUbicacion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabelUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUbicacion.setText("Pablo Picasso, Las Glorias, Puerto Vallarta Jalisco");
        getContentPane().add(jLabelUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 360, 160));

        jLabelNombreHotel.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        jLabelNombreHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreHotel.setText("Hotel OK Sibilus");
        getContentPane().add(jLabelNombreHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, 130));

        jTextAreaRECIBO.setEditable(false);
        jTextAreaRECIBO.setColumns(20);
        jTextAreaRECIBO.setRows(5);
        jScrollPanelEscritura.setViewportView(jTextAreaRECIBO);

        getContentPane().add(jScrollPanelEscritura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 350, 430));

        jTextAreaFondo.setEditable(false);
        jTextAreaFondo.setColumns(20);
        jTextAreaFondo.setRows(5);
        jTextAreaFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextAreaFondo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 350, 630));

        jButtonMenu.setText("MENU");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 100, 30));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        Fondo2.setText("jLabel1");
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 470, 340));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        Fondo.setText(" ");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 470, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        // TODO add your handling code here:
        Menu men=new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabelLema;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreHotel;
    private javax.swing.JLabel jLabelRecibo;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPanelEscritura;
    private javax.swing.JTextArea jTextAreaFondo;
    private javax.swing.JTextArea jTextAreaRECIBO;
    // End of variables declaration//GEN-END:variables
}
