/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;


/**
 *
 * @author Mario Garcia
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    MySqlConn objConn=new MySqlConn();
    
    public Registro(MySqlConn conn){
        this.objConn=objConn;
        initComponents();
    }
    
    public Registro() {
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        Calendar min = Calendar.getInstance();
        Calendar fecha = new GregorianCalendar();
        min.add(Calendar.DAY_OF_MONTH, 1);
        jDateChooser1.setMinSelectableDate(min.getTime());
        int año, mes, dia;
        año = fecha.get(Calendar.YEAR);
        mes = fecha.get(Calendar.MONTH);
        dia = fecha.get(Calendar.DAY_OF_MONTH);
        jLabelFecha.setText("Fecha actual : "+dia+" / "+(mes+1)+" / "+año);
        
        jTextFieldNombreCliente.setBorder(null);
        jTextFieldNombreCliente.setOpaque(false);
        jTextFieldNombreCliente.setBackground(new Color(0,0,0,48));
        jTextFieldCiudadOrigen.setBorder(null);
        jTextFieldCiudadOrigen.setOpaque(false);
        jTextFieldCiudadOrigen.setBackground(new Color(0,0,0,48));
        jTextFieldTotalPersonas.setBorder(null);
        jTextFieldTotalPersonas.setOpaque(false);
        jTextFieldTotalPersonas.setBackground(new Color(0,0,0,48));
        jComboBoxTipoHabitacion.setBorder(null);
        jComboBoxTipoHabitacion.setOpaque(false);
        jButtonRegistrarCliente.setOpaque(false);
        jButtonRegistrarCliente.setBackground(new Color(0,0,0,32));
        jButtonRegresar.setOpaque(false);
        jButtonRegresar.setBackground(new Color(0,0,0,32));
        
        
        //jLabelMax1.setVisible(false);
        jLabelMax2.setVisible(false);
        jLabelMax3.setVisible(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jTextFieldCiudadOrigen = new javax.swing.JTextField();
        jTextFieldTotalPersonas = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBoxTipoHabitacion = new javax.swing.JComboBox<>();
        jLabelMax1 = new javax.swing.JLabel();
        jLabelMax2 = new javax.swing.JLabel();
        jLabelMax3 = new javax.swing.JLabel();
        jButtonRegistrarCliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoh1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 140));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setText("Registro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 180, 70));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Nombre del cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 210, 30));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setText("Tipo de habitacion: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 60));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setText("Ciudad de origen:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 190, 40));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setText("Total de personas:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 200, 30));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel7.setText("Fecha de salida:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 180, 30));

        jTextFieldNombreCliente.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldNombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 270, 40));

        jTextFieldCiudadOrigen.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldCiudadOrigen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldCiudadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 270, 40));

        jTextFieldTotalPersonas.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldTotalPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldTotalPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 120, 40));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 270, 40));

        jComboBoxTipoHabitacion.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jComboBoxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Doble", "Triple" }));
        jComboBoxTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 270, 40));

        jLabelMax1.setText("*2 Personas P/Habitacion.");
        getContentPane().add(jLabelMax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 180, 20));

        jLabelMax2.setText("*4 Personas P/Habitacion.");
        getContentPane().add(jLabelMax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 170, 20));

        jLabelMax3.setText("*6 Personas P/Habitacion.");
        getContentPane().add(jLabelMax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 170, 20));

        jButtonRegistrarCliente.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jButtonRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarCliente.setText("Registrar");
        jButtonRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 190, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setText("*Solo una persona extra por habitacion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 200, 20));

        jButtonRegresar.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("<- Regresar");
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoHabitacionActionPerformed
        // TODO add your handling code here:
        String hab;
        String totalpersonas;
        totalpersonas = jTextFieldTotalPersonas.getText();
        
        hab = jComboBoxTipoHabitacion.getSelectedItem().toString();
        
        if(hab == "Sencilla"){
        jLabelMax1.setVisible(true);
        jLabelMax2.setVisible(false);
        jLabelMax3.setVisible(false);
    }else if(hab == "Doble"){
        jLabelMax1.setVisible(false);
        jLabelMax2.setVisible(true);
        jLabelMax3.setVisible(false);
    }else if(hab == "Triple"){
        jLabelMax1.setVisible(false);
        jLabelMax2.setVisible(false);
        jLabelMax3.setVisible(true);
    }
        
        
    }//GEN-LAST:event_jComboBoxTipoHabitacionActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarClienteActionPerformed
        // TODO add your handling code here:
        String nombre,ciudad,tipo,total,fechasalida,parte1,parte2,query, fechaActual;
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        nombre=this.jTextFieldNombreCliente.getText().trim();
        ciudad=this.jTextFieldCiudadOrigen.getText().trim();
        tipo=jComboBoxTipoHabitacion.getSelectedItem().toString();
        total=this.jTextFieldTotalPersonas.getText().trim();
        fechasalida=dFormat.format(jDateChooser1.getDate());
        
        Calendar fecha = new GregorianCalendar();
        int año, mes, dia;
        año = fecha.get(Calendar.YEAR);
        mes = fecha.get(Calendar.MONTH);
        dia = fecha.get(Calendar.DAY_OF_MONTH);
        
        fechaActual= (dia+"-"+(mes+1)+"-"+año);
            
        
        parte1="insert into clientes values (";
        parte2="'"+nombre+"','"+ciudad+"','"+tipo+"','"+total+"','"+fechasalida+"','"+fechaActual+"')";
        query=parte1+parte2;
        System.out.println(query);
        int j=this.objConn.Update(query);
        if(j>0){
           JOptionPane.showMessageDialog(this, "Cliente registrado");
            System.out.println("Cliente Registrado");
        }
        
        
        
    }//GEN-LAST:event_jButtonRegistrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonRegistrarCliente;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxTipoHabitacion;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMax1;
    private javax.swing.JLabel jLabelMax2;
    private javax.swing.JLabel jLabelMax3;
    private javax.swing.JTextField jTextFieldCiudadOrigen;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldTotalPersonas;
    // End of variables declaration//GEN-END:variables
}
