/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Pavilion
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    
    MySqlConn objConn=new MySqlConn();
    
    public Registrar(MySqlConn conn){
        this.objConn=objConn;
        initComponents();
    }
    
    
    public Registrar() {
        initComponents();
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setOpaque(false);
        jTextFieldNombre.setBackground(new Color(0,0,0,48));
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.setOpaque(false);
        jTextFieldUsuario.setBackground(new Color(0,0,0,48));
        jPasswordFieldContraseña.setBorder(null);
        jPasswordFieldContraseña.setOpaque(false);
        jPasswordFieldContraseña.setBackground(new Color (0,0,0,48));
        jPasswordFieldConfirmarContraseña.setBorder(null);
        jPasswordFieldConfirmarContraseña.setOpaque(false);
        jPasswordFieldConfirmarContraseña.setBackground(new Color (0,0,0,48));
        jButtonAceptar.setOpaque(false);
        jButtonAceptar.setBackground(new Color(0,0,0,32));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jPasswordFieldConfirmarContraseña = new javax.swing.JPasswordField();
        jButtonAceptar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setText("Confirmar Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 250, 40));

        jTextFieldUsuario.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 250, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoh1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 140, 140));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        jLabel7.setText("Registrar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 190, 50));

        jPasswordFieldContraseña.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jPasswordFieldContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 250, 40));

        jPasswordFieldConfirmarContraseña.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jPasswordFieldConfirmarContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jPasswordFieldConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 250, 40));

        jButtonAceptar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 190, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 449));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        //serializacion del proyecto
        String usuario,password,parte1,parte2,query, passwordconf, password1, nombre;
        nombre=this.jTextFieldNombre.getText().trim();
        usuario=this.jTextFieldUsuario.getText().trim();
        char[] passw=this.jPasswordFieldContraseña.getPassword();
        char[] passwconf=this.jPasswordFieldConfirmarContraseña.getPassword();
        password1=new String(passw);
        passwordconf=new String(passwconf);
        
        if(password1.equals(passwordconf)){
        
        password=new String(passw);
        parte1="insert into users values (";
        parte2="'"+nombre+"',"+"'"+usuario+"',"+" MD5('"+password+"'))";
        query=parte1+parte2;
        System.out.println(query);
        int j=this.objConn.Update(query);
        if(j>0){
           JOptionPane.showMessageDialog(this, "Cuenta Registrada...");
            System.out.println("Cuenta Registrada...");
            
        }
        
        Ingresar ing = new Ingresar();
        ing.setVisible(true);
        dispose();
        
        }else{
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
        }
       
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordFieldConfirmarContraseña;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
