/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario Garcia
 */
public class Salida extends javax.swing.JFrame {

    /**
     * Creates new form Salida
     */
    MySqlConn objConn=new MySqlConn();
    
    public Salida(MySqlConn conn){
        this.objConn=objConn;
        initComponents(); 
    }
    
    
    public Salida() {
        initComponents();
        jTextFieldNumHabitacion.setBorder(null);
        jTextFieldNumHabitacion.setOpaque(false);
        jTextFieldNumHabitacion.setBackground(new Color(0,0,0,48));
        jTextFieldinfo.setBorder(null);
        jTextFieldinfo.setOpaque(false);
        jTextFieldinfo.setBackground(new Color(0,0,0,48));
        jButtonBuscar.setOpaque(false);
        jButtonBuscar.setBackground(new Color(0,0,0,32));
        jTextFieldinfo1.setBorder(null);
        jTextFieldinfo1.setOpaque(false);
        jTextFieldinfo1.setBackground(new Color(0,0,0,48));
        jButtonBaja.setOpaque(false);
        jButtonBaja.setBackground(new Color(0,0,0,32));
        jButtonRegresar.setOpaque(false);
        jButtonRegresar.setBackground(new Color(0,0,0,32));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNumHabitacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldinfo = new javax.swing.JTextField();
        jTextFieldinfo1 = new javax.swing.JTextField();
        jButtonBaja = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel1.setText("Salida");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese el numero de habitacion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 360, 40));

        jTextFieldNumHabitacion.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextFieldNumHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldNumHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 140, 40));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Informacion del cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 270, 20));

        jButtonBuscar.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 140, 40));

        jTextFieldinfo.setEditable(false);
        jTextFieldinfo.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jTextFieldinfo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 630, 40));

        jTextFieldinfo1.setEditable(false);
        jTextFieldinfo1.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jTextFieldinfo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldinfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 630, 40));

        jButtonBaja.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jButtonBaja.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBaja.setText("Dar de baja");
        jButtonBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 210, 50));

        jButtonRegresar.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("<- Regresar");
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 140, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        int h1;
        String h = this.jTextFieldNumHabitacion.getText().trim();
        h1 = Integer.parseInt(h);
        List<Clientes> lista = new ArrayList<Clientes>();

        try{
            Statement st = objConn.conn.createStatement();
            String query1 = "select * from clientes";
            ResultSet rs = st.executeQuery(query1);
            String nombre1, ciudad1, tipo1, fechasalida1, fechaentrada1;
            int total1, habitacion1;
            lista.removeAll(lista);
            while(rs.next()){
                nombre1 = rs.getString("nombre");
                ciudad1 = rs.getString("ciudad");
                tipo1 = rs.getString("tipo");
                fechasalida1 = rs.getString("fechasalida");
                fechaentrada1 = rs.getString("fechaentrada");
                total1 = rs.getInt("total");
                habitacion1 = rs.getInt("habitacion");
                Clientes c;
                c = new Clientes(nombre1, ciudad1, tipo1,total1,fechasalida1, fechaentrada1, habitacion1);
                
                if(h1 == habitacion1){
                    
                    System.out.println("busca: "+h+"hab1: "+habitacion1);
                    jTextFieldinfo.setText("Nombre: " + nombre1 + ", Cudad: " + ciudad1 + ", Tipo de Habitacion: " + tipo1 + ", Total de Personas: " + total1);
                    jTextFieldinfo1.setText("Fecha de salida: " + fechasalida1 + ", Fecha de entrada: " + fechaentrada1 + ", Habitacion: " + habitacion1);
                }
                
                //System.out.println("busca: "+h+"hab1: "+habitacion1);
                lista.add(c);
            }
            
        }catch(SQLException sqle){
            System.out.println("Error SQL....." + sqle);
        }
        
        
        
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        // TODO add your handling code here:
        String habitacion = this.jTextFieldNumHabitacion.getText().trim();
        if(habitacion.isEmpty()){
            JOptionPane.showMessageDialog(this, "Numero de habitacion vacio");
            
        }else{
            String query= "delete from clientes where habitacion="+"'"+habitacion+"'";
            int j=this.objConn.Update(query);
            if(j>0)
                JOptionPane.showMessageDialog(this, "Baja realizada ");
            else
                JOptionPane.showMessageDialog(this, "La baja no se pudo realizar ");
        }
        
        
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldNumHabitacion;
    private javax.swing.JTextField jTextFieldinfo;
    private javax.swing.JTextField jTextFieldinfo1;
    // End of variables declaration//GEN-END:variables
}
